### ISSUE TITLE
Xorg no longer rootless

### ISSUE THREAD

**Issue by Vargblood** [geminis3/envycontrol#12]
Hi everyone and thank you for your great work and this project. I switched recently from Optimus manager to envycontrol and everything is working fine. I noticed that my Xorg session under Gnome now runs as root. Before the change, the process ran rootless.
Is this change possibly related to envycontrol or the gdm package I changed from gdm-Prime to the original gdm package? Has anyone who has also changed noticed the same behavior?

**Comment by DaVikingMan** [comment]
This page might help you : https://wiki.archlinux.org/index.php/Xorg#Rootless_Xorg

**Comment by Vargblood** [comment]
> This page might help you : https://wiki.archlinux.org/index.php/Xorg#Rootless_Xorg

I know this page. Gdm run xorg rootless by default but not with my current configuration. Now I’m looking for the cause.

**Comment by DaVikingMan** [comment]
Are you using KMS?

**Comment by Vargblood** [comment]
> Which init system and linux distro are you using? Also, what's the output of `cat /proc/cmdline`?

I use arch linux with systemd. 

Output of `cat /proc/cmdline`:

`pti=on page_alloc.shuffle=1 BOOT_IMAGE=/@/boot/vmlinuz-linux-hardened root=UUID=[UUID] rw rootflags=subvol=@ cryptdevice=/dev/nvme0n1p2:arch splash apparmor=1 security=apparmor intel_iommu=on iommu=pt`

I replaced the actual UUID with [UUID].

**Comment by DaVikingMan** [comment]
According to the output, it seems like KMS for nvidia isn't enabled. You can try the instructions on this page to enable it: https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

**Comment by Vargblood** [comment]
This is the solution. Now Xorg is run as a normal user. Two more questions:
Did Optimus manager set this option automatically and that's why I never noticed?
Do I need to pay attention to anything else in the future when this option (nvidia-drm.modeset=1) is set or is this standard with an nvidia card anyway?

Thanks for your very helpful solution description and your great help.

**Comment by DaVikingMan** [comment]
1. Optimus-manager doesn't add this option to the kernel parameters so It might be related to gdm-Prime instead of optimus-manager as that package does add some patches for hybrid graphics.
2. Although this isn't pre-enabled in nvidia cards, it should be enabled as it enables the card to do direct rendering, which helps the kernel to access direct rendering manager(https://en.wikipedia.org/wiki/Direct_Rendering_Manager for more info regarding this) and does increase some performance. This option shouldn't cause any problems so there isn't a need to pay attention to this option.

**Comment by Vargblood** [comment]
Awesome. Thank you. Maybe someone should add this to the wiki of this project for those who come from Optimus manager and used the gdm-prime package.
